import type { CountryCode, Metadata, Snowflake } from './resources/globals';
import type {
	APIMessageAnalysis,
	MessageError,
	MessageStatus,
	MessageType,
} from './resources/message';
import { WebhookEventType } from './resources/webhooks';

export interface WebhookBase<
	Type extends WebhookEventType,
	Data extends object,
> {
	/** Webhook event identifier generated by Rewrite. */
	id: Snowflake;

	/** Timestamp when Rewrite created the event payload. */
	createdAt: string;

	/** Webhook event type. */
	type: Type;

	/** Whether Rewrite created this event while the project was in sandbox mode. */
	sandbox: boolean;

	/** Event payload. */
	data: Data;
}

export interface WebhookOTPMetadata {
	prefix: string;
	expiresIn: number;
	expiresAt: string;
}

export interface WebhookMessagePayload {
	id: Snowflake;
	projectId: Snowflake;
	contact: string | null;
	contactId: Snowflake | null;
	to: string;
	tags: Metadata;
	sandbox: boolean;
	type: MessageType;
	status: MessageStatus;
	content: string;
	country: CountryCode;
	analysis: APIMessageAnalysis;
	error: MessageError | null;
	deliveredAt: string | null;
	scheduledAt: string | null;
	templateId: Snowflake | null;
	otp?: WebhookOTPMetadata;
}

export interface WebhookBatchPayload {
	id: Snowflake;
	projectId: Snowflake;
	ids: Snowflake[];
}

export type WebhookSMSOTPEvent = WebhookBase<
	WebhookEventType.SMSOTP,
	WebhookMessagePayload & {
		type: MessageType.OTP;
		otp: WebhookOTPMetadata;
	}
>;

export type WebhookMessageSentEvent = WebhookBase<
	WebhookEventType.MessageSent,
	WebhookMessagePayload & { type: MessageType.SMS; status: MessageStatus.Sent }
>;

export type WebhookMessageBatchEvent = WebhookBase<
	WebhookEventType.MessageBatch,
	WebhookBatchPayload
>;

export type WebhookMessageQueuedEvent = WebhookBase<
	WebhookEventType.MessageQueued,
	WebhookMessagePayload & {
		type: MessageType.SMS;
		status: MessageStatus.Queued;
	}
>;

export type WebhookMessageFailedEvent = WebhookBase<
	WebhookEventType.MessageFailed,
	WebhookMessagePayload & { status: MessageStatus.Failed; error: MessageError }
>;

export type WebhookMessageCanceledEvent = WebhookBase<
	WebhookEventType.MessageCanceled,
	WebhookMessagePayload & {
		type: MessageType.SMS;
		status: MessageStatus.Canceled;
	}
>;

export type WebhookMessageDeliveredEvent = WebhookBase<
	WebhookEventType.MessageDelivered,
	WebhookMessagePayload & {
		type: MessageType.SMS;
		status: MessageStatus.Delivered;
	}
>;

export type WebhookMessageReceivedEvent = WebhookBase<
	WebhookEventType.MessageReceived,
	WebhookMessagePayload & {
		type: MessageType.SMS;
		status: MessageStatus.Received;
	}
>;

export type WebhookMessageScheduledEvent = WebhookBase<
	WebhookEventType.MessageScheduled,
	WebhookMessagePayload & {
		type: MessageType.SMS;
		status: MessageStatus.Scheduled;
	}
>;

export type WebhookEvent =
	| WebhookSMSOTPEvent
	| WebhookMessageSentEvent
	| WebhookMessageBatchEvent
	| WebhookMessageQueuedEvent
	| WebhookMessageFailedEvent
	| WebhookMessageCanceledEvent
	| WebhookMessageDeliveredEvent
	| WebhookMessageReceivedEvent
	| WebhookMessageScheduledEvent;

export function isWebhookSMSOTPEvent(event: WebhookEvent) {
	return event.type === WebhookEventType.SMSOTP;
}

export function isWebhookMessageSentEvent(event: WebhookEvent) {
	return event.type === WebhookEventType.MessageSent;
}

export function isWebhookMessageBatchEvent(event: WebhookEvent) {
	return event.type === WebhookEventType.MessageBatch;
}

export function isWebhookMessageQueuedEvent(event: WebhookEvent) {
	return event.type === WebhookEventType.MessageQueued;
}

export function isWebhookMessageFailedEvent(event: WebhookEvent) {
	return event.type === WebhookEventType.MessageFailed;
}

export function isWebhookMessageCanceledEvent(event: WebhookEvent) {
	return event.type === WebhookEventType.MessageCanceled;
}

export function isWebhookMessageDeliveredEvent(event: WebhookEvent) {
	return event.type === WebhookEventType.MessageDelivered;
}

export function isWebhookMessageReceivedEvent(event: WebhookEvent) {
	return event.type === WebhookEventType.MessageReceived;
}

export function isWebhookMessageScheduledEvent(event: WebhookEvent) {
	return event.type === WebhookEventType.MessageScheduled;
}
